from __future__ import annotations

# Legacy seed snapshot retained for reproducibility of the 2026-05 APAC pass.
# Do not extend this file for new countries or rounds; use reusable import,
# structured-growth, and quality-gate scripts with external input/config instead.

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from isite2.growth.evidence_curation import run_pending_evidence_curation
from isite2.growth.evidence_intake import (
    CandidateDraft,
    load_effective_source_registry,
    validate_candidate_draft,
)
from isite2.growth.evidence_store import EvidenceCurationStore
from isite2.growth.overlay_sync import sync_overlay_to_active_repository
from isite2.repositories.sqlalchemy import SQLAlchemyScanRunRepository

DB_URL = "sqlite+pysqlite:///outputs/isite2_dev.db"
OUTPUT_DIR = Path("outputs") / "regional_scan_loop"
SOURCE_TYPE = "apac_high_value_seed"
SOURCE_DATE = "2026-05-13"

APAC_COUNTRIES = ["Sri Lanka", "Cambodia", "Maldives"]


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Seed APAC high-value property candidates with scene-specific hard metrics."
        )
    )
    parser.add_argument("--countries", nargs="+", default=APAC_COUNTRIES)
    parser.add_argument("--skip-sync", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    countries = set(args.countries)
    registry = load_effective_source_registry()
    planned = [
        draft
        for draft in _drafts(registry)
        if draft.country in countries
    ]

    accepted: list[CandidateDraft] = []
    rejected: list[dict[str, Any]] = []
    for draft in planned:
        validation = validate_candidate_draft(draft)
        if validation.accepted:
            accepted.append(draft)
        else:
            rejected.append(
                {
                    "country": draft.country,
                    "property_name": draft.property_name,
                    "scene_type": draft.scene_type,
                    "issues": validation.issues,
                }
            )

    raw_ids: list[str] = []
    write_stats = {
        "new_evidence": 0,
        "changed_evidence": 0,
        "duplicate_unchanged": 0,
    }
    curation = None
    sync = None
    if accepted and not args.dry_run:
        store = EvidenceCurationStore(database_url=DB_URL)
        for draft in accepted:
            result = store.upsert_candidate_evidence(
                draft,
                source_type=SOURCE_TYPE,
            )
            raw_ids.append(result.raw_evidence_id)
            if result.duplicate_unchanged:
                write_stats["duplicate_unchanged"] += 1
            elif result.is_changed_evidence:
                write_stats["changed_evidence"] += 1
            elif result.is_new_evidence:
                write_stats["new_evidence"] += 1

        curation = run_pending_evidence_curation(store=store, output_dir=OUTPUT_DIR)
        if not args.skip_sync:
            repository = SQLAlchemyScanRunRepository.from_url(
                DB_URL,
                storage_mode="sqlite",
            )
            sync = sync_overlay_to_active_repository(repository)

    summary = {
        "mode": "apac_high_value_seed",
        "timestamp_utc": datetime.now(UTC).isoformat(),
        "countries": sorted(countries),
        "planned_count": len(planned),
        "accepted_for_write_count": len(accepted),
        "rejected_count": len(rejected),
        "rejected": rejected,
        "raw_evidence_ids": raw_ids,
        "write_stats": write_stats,
        "curation": _curation_summary(curation),
        "overlay_sync": _sync_summary(sync),
        "accepted_candidates": [
            {
                "country": draft.country,
                "city": draft.city,
                "property_name": draft.property_name,
                "scene_type": draft.scene_type,
                "field_group": draft.field_group,
                "indicator_name": draft.indicator_name,
                "source_name": draft.source_name,
                "source_url": draft.source_url,
            }
            for draft in accepted
        ],
        "firecrawl_credits_used": 0,
    }
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    summary_path = OUTPUT_DIR / f"apac_high_value_seed_{timestamp}.json"
    report_path = summary_path.with_suffix(".md")
    summary["summary_path"] = str(summary_path)
    summary["report_path"] = str(report_path)
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n")
    report_path.write_text(_render_report(summary), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def _drafts(registry: dict[str, Any]) -> list[CandidateDraft]:
    return [
        _draft(
            registry,
            country="Sri Lanka",
            city="Western Province",
            property_name="Bandaranaike International Airport",
            scene_type="airport_terminal",
            annual_visits=8_500_000,
            latitude=7.1808,
            longitude=79.8841,
            geocode_precision="airport terminal centroid",
            field_group="annual_passenger_throughput",
            indicator_name="annual_passenger_throughput",
            field_value="2024 passenger movements: over 8.5 million passengers",
            source_name="Aviation Voice",
            source_tier="Tier 2",
            source_url="https://aviationvoice.lk/bandaranaike-international-airport-bia-handled-over-8-5-million-passengers-in-2024-report/",
            source_date="2025-01-21",
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/22_boeing_772_app_cmb.jpg/330px-22_boeing_772_app_cmb.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Bandaranaike_International_Airport",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="R. Premadasa Stadium",
            scene_type="stadium",
            annual_visits=525_000,
            latitude=6.93972,
            longitude=79.87194,
            geocode_precision="stadium centroid",
            field_group="seat_count",
            indicator_name="seat_count",
            field_value="Stadium capacity: 35,000 spectators",
            source_name="Wikipedia / Cricinfo venue profile",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/R._Premadasa_Stadium",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/The_clouds_roll_in.jpg/330px-The_clouds_roll_in.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/R._Premadasa_Stadium",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="One Galle Face Mall",
            scene_type="mall_mixed_use",
            annual_visits=892_000,
            latitude=6.9295,
            longitude=79.8449,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Retail stores spanning over 480,000 square feet",
            source_name="INVEST.LK",
            source_tier="Tier 2",
            source_url="https://www.invest.lk/mall-one-galle-face-transforms-local-retail-landscape/",
            source_date="2018-02-15",
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/UG-LK_Photowalk_-_OneGalleFace_and_surroundings_-_2017-03-12_%2813%29.jpg/330px-UG-LK_Photowalk_-_OneGalleFace_and_surroundings_-_2017-03-12_%2813%29.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/One_Galle_Face",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Cinnamon Life at City of Dreams",
            scene_type="luxury_hotel_mice",
            annual_visits=618_300,
            latitude=6.9247,
            longitude=79.8536,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="687 guest rooms including 37 suites",
            source_name="Cvent Supplier Network",
            source_tier="Tier 2",
            source_url="https://www.cvent.com/venues/colombo/resort/cinnamon-life-at-city-of-dreams/venue-be1da351-c8fb-4ff4-b26d-1afa3bac6e17",
            source_date=SOURCE_DATE,
            hero_url="https://images.cvent.com/csn/be1da351-c8fb-4ff4-b26d-1afa3bac6e17/images/a42b54e16b324921b0e6759f6268c1d9_large!_!5e2250cbfe9380ff6a9469ba1272aca8.jpg",
            hero_source_name="Cvent Supplier Network",
            hero_source_url="https://www.cvent.com/venues/colombo/resort/cinnamon-life-at-city-of-dreams/venue-be1da351-c8fb-4ff4-b26d-1afa3bac6e17",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Shangri-La Colombo",
            scene_type="luxury_hotel_mice",
            annual_visits=450_000,
            latitude=6.9281,
            longitude=79.8449,
            geocode_precision="hotel venue centroid",
            field_group="ballroom_capacity",
            indicator_name="ballroom_capacity",
            field_value="Shangri-La Ballroom capacity: 3,000 reception, 2,500 theatre, 1,580 sqm",
            source_name="Shangri-La Colombo",
            source_tier="Tier 1",
            source_url="https://www.shangri-la.com/colombo/shangrila/meetings-events/event-spaces/",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/UG-LK_Photowalk_-_OneGalleFace_and_surroundings_-_2017-03-12_%2813%29.jpg/330px-UG-LK_Photowalk_-_OneGalleFace_and_surroundings_-_2017-03-12_%2813%29.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Shangri-La_Colombo",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Bandaranaike Memorial International Conference Hall",
            scene_type="convention_center",
            annual_visits=None,
            latitude=6.90167,
            longitude=79.87278,
            geocode_precision="convention venue centroid",
            field_group="exhibition_area",
            indicator_name="exhibition_area",
            field_value="Sirimavo Bandaranaike Memorial Exhibition Centre floor area: 4,500 sqm",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/Bandaranaike_Memorial_International_Conference_Hall",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/20160122_Sri_Lanka_3645_Colombo_sRGB_%2825144304823%29.jpg/330px-20160122_Sri_Lanka_3645_Colombo_sRGB_%2825144304823%29.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Bandaranaike_Memorial_International_Conference_Hall",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Sri Lanka Exhibition and Convention Centre",
            scene_type="convention_center",
            annual_visits=None,
            latitude=6.9297,
            longitude=79.8612,
            geocode_precision="convention venue centroid",
            field_group="exhibition_area",
            indicator_name="exhibition_area",
            field_value="Total exhibit space: 4,000 sq m",
            source_name="Meetings & Conventions",
            source_tier="Tier 2",
            source_url="https://www.meetings-conventions.com/Meeting-Event-Venues/Colombo-Sri-Lanka/Convention-Center/Sri-Lanka-Exhibition-Convention-Centre-p53227102",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Sri_lanka_colombo.JPG/330px-Sri_lanka_colombo.JPG",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Sri_Lanka_Exhibition_and_Convention_Centre",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="World Trade Center Colombo",
            scene_type="office_government",
            annual_visits=5_160_000,
            latitude=6.9332,
            longitude=79.8436,
            geocode_precision="office tower centroid",
            field_group="tower_height",
            indicator_name="tower_height",
            field_value="Twin office towers: 152 m height and 43 total floors each",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/World_Trade_Center_Colombo",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/UG-LK_Photowalk_-_WTC_and_surroundings_-_2017-03-12_%2813%29.jpg/330px-UG-LK_Photowalk_-_WTC_and_surroundings_-_2017-03-12_%2813%29.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/World_Trade_Center_Colombo",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="ITC Ratnadipa",
            scene_type="luxury_hotel_mice",
            annual_visits=316_800,
            latitude=6.9243,
            longitude=79.8469,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="352 guest rooms, suites and service apartments",
            source_name="ITC Hotels press release",
            source_tier="Tier 1",
            source_url="https://itcportal.com/media-centre/press-releases/itc-ratnadipa-a-magnificent-icon-of-responsible-luxury-launched-in-colombo.html",
            source_date="2024-04-25",
            hero_url="https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/ITC_Ratnadipa_2024.jpg/330px-ITC_Ratnadipa_2024.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/ITC_Ratnadipa",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Cinnamon Grand Colombo",
            scene_type="luxury_hotel_mice",
            annual_visits=450_900,
            latitude=6.9187,
            longitude=79.8486,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="475 rooms and 26 suites",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/Cinnamon_Grand_Colombo",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Cinnamon_Grand%2C_Colombo%2C_Reception.jpg/330px-Cinnamon_Grand%2C_Colombo%2C_Reception.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Cinnamon_Grand_Colombo",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Kandy",
            property_name="Kandy City Centre",
            scene_type="mall_mixed_use",
            annual_visits=880_000,
            latitude=7.2925,
            longitude=80.6375,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Commercial and retail complex floor area: 44,000 sqm",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/Kandy_City_Centre",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Kandy_city_centre.JPG/960px-Kandy_city_centre.JPG",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://commons.wikimedia.org/wiki/File:Kandy_city_centre.JPG",
        ),
        _draft(
            registry,
            country="Sri Lanka",
            city="Colombo",
            property_name="Colombo City Centre",
            scene_type="mall_mixed_use",
            annual_visits=371_600,
            latitude=6.9170,
            longitude=79.8581,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Mall retail area: 200,000 square feet",
            source_name="LankaPropertyWeb",
            source_tier="Tier 2",
            source_url="https://www.lankapropertyweb.com/property-news/colombo-city-centre/",
            source_date=SOURCE_DATE,
            hero_url="https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Colombo_City_Centre.jpg/330px-Colombo_City_Centre.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Colombo_City_Centre",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Kandal Province",
            property_name="Techo International Airport",
            scene_type="airport_terminal",
            annual_visits=13_000_000,
            latitude=11.0827,
            longitude=104.8797,
            geocode_precision="airport terminal centroid",
            field_group="terminal_capacity",
            indicator_name="terminal_capacity",
            field_value="Phase 1 capacity: over 13 million passengers per year",
            source_name="VINCI Airports",
            source_tier="Tier 1",
            source_url="https://vinci-airports.com/en/our-airports/cambodia/phnom-penh-airport/",
            source_date=SOURCE_DATE,
            hero_url="https://vinci-airports.com/wp-content/uploads/2024/07/KTI3-scaled.jpg",
            hero_source_name="VINCI Airports",
            hero_source_url="https://vinci-airports.com/en/our-airports/cambodia/phnom-penh-airport/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Siem Reap Province",
            property_name="Siem Reap-Angkor International Airport",
            scene_type="airport_terminal",
            annual_visits=7_000_000,
            latitude=13.3692,
            longitude=104.2236,
            geocode_precision="airport terminal centroid",
            field_group="terminal_capacity",
            indicator_name="terminal_capacity",
            field_value="Designed capacity: 7 million passengers per year",
            source_name="Associated Press",
            source_tier="Tier 2",
            source_url="https://apnews.com/article/cfcd7ca4ce3d042011937916448cdb91",
            source_date="2023-10-16",
            hero_url="https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Techo_International_Airport_Terminal.jpg/330px-Techo_International_Airport_Terminal.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://en.wikipedia.org/wiki/Siem_Reap%E2%80%93Angkor_International_Airport",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Morodok Techo National Stadium",
            scene_type="stadium",
            annual_visits=900_000,
            latitude=11.6393,
            longitude=104.8640,
            geocode_precision="stadium centroid",
            field_group="seat_count",
            indicator_name="seat_count",
            field_value="Stadium capacity: 60,000 seats",
            source_name="StadiumDB",
            source_tier="Tier 2",
            source_url="https://stadiumdb.com/stadiums/cam/morodok_techo_national_stadium",
            source_date=SOURCE_DATE,
            hero_url="https://stadiumdb.com/pictures/stadiums/cam/morodok_techo_national_stadium/morodok_techo_national_stadium01.jpg",
            hero_source_name="StadiumDB",
            hero_source_url="https://stadiumdb.com/stadiums/cam/morodok_techo_national_stadium",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="AEON Mall Mean Chey",
            scene_type="mall_mixed_use",
            annual_visits=1_960_000,
            latitude=11.5091,
            longitude=104.9251,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Gross leasable area: approx. 98,000 sqm",
            source_name="AEON MALL Cambodia",
            source_tier="Tier 1",
            source_url="https://www.aeonmallcambodia.com.kh/aeon-mall-mean-chey/",
            source_date=SOURCE_DATE,
            hero_url="https://www.aeonmallcambodia.com/wp-content/uploads/2023/06/AMMC-MALL.jpg",
            hero_source_name="AEON MALL Cambodia",
            hero_source_url="https://www.aeonmallcambodia.com.kh/aeon-mall-mean-chey/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="AEON Mall Sen Sok City",
            scene_type="mall_mixed_use",
            annual_visits=1_700_000,
            latitude=11.5945,
            longitude=104.8840,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Gross leasable area: approx. 85,000 sqm",
            source_name="AEON MALL Cambodia",
            source_tier="Tier 1",
            source_url="https://www.aeonmallcambodia.com/aeon-mall-sen-sok-city/",
            source_date=SOURCE_DATE,
            hero_url="https://www.aeonmallcambodia.com/wp-content/uploads/2023/03/%E2%98%85SenSokCity%E3%83%A2%E3%83%BC%E3%83%AB%E6%A6%82%E8%A6%81%E4%BD%BF%E7%94%A8%EF%BC%88%E5%8A%A0%E5%B7%A5%E6%B8%88%E3%81%BF%EF%BC%89-scaled.jpg",
            hero_source_name="AEON MALL Cambodia",
            hero_source_url="https://www.aeonmallcambodia.com/aeon-mall-sen-sok-city/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Hyatt Regency Phnom Penh",
            scene_type="luxury_hotel_mice",
            annual_visits=222_300,
            latitude=11.5656,
            longitude=104.9272,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="247 rooms; 1,400 sqm meeting and event space",
            source_name="Hyatt Newsroom",
            source_tier="Tier 1",
            source_url="https://newsroom.hyatt.com/news-releases?item=124035",
            source_date="2021-01-06",
            hero_url="https://images.cvent.com/CSN/e042ab5f-e1e8-4794-b447-6a799b202aa3/images/74298fb6ac6e4109bc7c188a7f5bf04a_LARGE!_!32c55389b86cdb3b53fd2d9f29411fb7.jpg",
            hero_source_name="Cvent Supplier Network",
            hero_source_url="https://www.cvent.com/venues/phnom-penh/hotel/hyatt-regency-phnom-penh/venue-e042ab5f-e1e8-4794-b447-6a799b202aa3",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Vattanac Capital",
            scene_type="office_government",
            annual_visits=4_680_000,
            latitude=11.5767,
            longitude=104.9210,
            geocode_precision="office tower centroid",
            field_group="tower_height",
            indicator_name="tower_height",
            field_value="188-metre, 39-storey tower with Grade A offices",
            source_name="Vattanac Capital",
            source_tier="Tier 1",
            source_url="https://www.vattanaccapital.com/company/about-us/",
            source_date=SOURCE_DATE,
            hero_url="https://www.vattanaccapital.com/wp-content/uploads/2022/08/06-Dec-2013-1920x1280-1.jpg",
            hero_source_name="Vattanac Capital",
            hero_source_url="https://www.vattanaccapital.com/company/about-us/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Canadia Tower",
            scene_type="office_government",
            annual_visits=3_840_000,
            latitude=11.5744,
            longitude=104.9188,
            geocode_precision="office tower centroid",
            field_group="floor_count",
            indicator_name="floor_count",
            field_value="32-storey Grade A commercial office building",
            source_name="OCIC",
            source_tier="Tier 1",
            source_url="https://www.ocic.com.kh/projects/canadia-tower",
            source_date=SOURCE_DATE,
            hero_url="https://cdn.prod.website-files.com/63f783e54b29372e31927b14/666bf377d29dd7ede339f461_Canadia%20Tower.jpg",
            hero_source_name="OCIC",
            hero_source_url="https://www.ocic.com.kh/projects/canadia-tower",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Exchange Square Phnom Penh",
            scene_type="office_government",
            annual_visits=1_985_000,
            latitude=11.5625,
            longitude=104.9247,
            geocode_precision="office tower centroid",
            field_group="office_gfa",
            indicator_name="office_gfa",
            field_value="Grade A office space: 39,700 sqm across 16 floors",
            source_name="Occupi marketplace profile",
            source_tier="Tier 2",
            source_url="https://citidirectportal.getoccupi.com/malls/exchange-square",
            source_date=SOURCE_DATE,
            hero_url="https://exchangesquare.com.kh/wp-content/uploads/2020/02/CONTACT.jpg",
            hero_source_name="Exchange Square Phnom Penh",
            hero_source_url="https://exchangesquare.com.kh/contact-us/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="AEON Mall Phnom Penh",
            scene_type="mall_mixed_use",
            annual_visits=1_620_000,
            latitude=11.5463,
            longitude=104.9334,
            geocode_precision="shopping mall centroid",
            field_group="gla",
            indicator_name="gla",
            field_value="Gross leasable area: 81,000 sqm",
            source_name="Malls.com",
            source_tier="Tier 2",
            source_url="https://www.malls.com/malls/aeon_mall_phnom_penh/",
            source_date=SOURCE_DATE,
            hero_url="https://www.aeonmallcambodia.com/wp-content/uploads/2023/06/6-scaled.jpg",
            hero_source_name="AEON MALL Cambodia",
            hero_source_url="https://www.aeonmallcambodia.com.kh/aeon-mall-phnom-penh/",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Rosewood Phnom Penh",
            scene_type="luxury_hotel_mice",
            annual_visits=157_500,
            latitude=11.5767,
            longitude=104.9210,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="175 rooms including 138 rooms, 37 suites and three signature suites",
            source_name="Rosewood Phnom Penh hotel brochure",
            source_tier="Tier 1",
            source_url="https://www.rosewoodhotels.com/content/dam/rosewoodhotels/property/phnom-penh/en/documents/RWPPN-hotel%20brochure.pdf",
            source_date=SOURCE_DATE,
            hero_url="https://www.rosewoodhotels.com/content/dam/rosewoodhotels/property/phnom-penh/en/images/overview/-dsc5307-y.jpg",
            hero_source_name="Rosewood Phnom Penh",
            hero_source_url="https://www.rosewoodhotels.com/en/phnom-penh/media/press-kit/hotel-fact-sheet",
        ),
        _draft(
            registry,
            country="Cambodia",
            city="Phnom Penh",
            property_name="Sofitel Phnom Penh Phokeethra",
            scene_type="luxury_hotel_mice",
            annual_visits=180_900,
            latitude=11.546306,
            longitude=104.933521,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="201 rooms and suites; eight meeting spaces",
            source_name="Sofitel Phnom Penh Phokeethra",
            source_tier="Tier 1",
            source_url="https://sofitel.accor.com/en/hotels/6526.html",
            source_date=SOURCE_DATE,
            hero_url="https://m.ahstatic.com/is/image/accorhotels/aja_p_6160-53",
            hero_source_name="Sofitel Phnom Penh Phokeethra",
            hero_source_url="https://sofitel.accor.com/en/hotels/6526.html",
        ),
        _draft(
            registry,
            country="Maldives",
            city="Kaafu Atoll",
            property_name="Velana International Airport",
            scene_type="airport_terminal",
            annual_visits=7_500_000,
            latitude=4.1918,
            longitude=73.5291,
            geocode_precision="airport terminal centroid",
            field_group="terminal_capacity",
            indicator_name="terminal_capacity",
            field_value="New 72,000 sqm terminal designed to handle 7.5 million passengers annually",
            source_name="Maldives Airports Company Limited",
            source_tier="Tier 1",
            source_url="https://www.macl.aero/corporate/media/pressreleases/114",
            source_date="2025-06-25",
            hero_url="https://www.macl.aero/img/logo_startup.png",
            hero_source_name="Maldives Airports Company Limited",
            hero_source_url="https://www.macl.aero/corporate/media/pressreleases/114",
        ),
        _draft(
            registry,
            country="Maldives",
            city="Male",
            property_name="National Football Stadium (Maldives)",
            scene_type="stadium",
            annual_visits=177_750,
            latitude=4.17408,
            longitude=73.51308,
            geocode_precision="stadium centroid",
            field_group="seat_count",
            indicator_name="seat_count",
            field_value="Seating capacity: 11,850",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/National_Football_Stadium_(Maldives)",
            source_date=SOURCE_DATE,
            hero_url="https://commons.wikimedia.org/wiki/Special:FilePath/Galolhu%20Dhandu.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://commons.wikimedia.org/wiki/Category:National_Football_Stadium_(Maldives)",
        ),
        _draft(
            registry,
            country="Maldives",
            city="South Male Atoll",
            property_name="CROSSROADS Event Hall",
            scene_type="convention_center",
            annual_visits=None,
            latitude=4.0215,
            longitude=73.4541,
            geocode_precision="convention venue centroid",
            field_group="peak_event_capacity",
            indicator_name="peak_event_capacity",
            field_value="Event Hall capacity: 300 theatre; hall area: 326 sqm",
            source_name="CROSSROADS Maldives",
            source_tier="Tier 1",
            source_url="https://crossroadsmaldives.com/events/",
            source_date=SOURCE_DATE,
            hero_url="https://crossroadsmaldives.com/wp-content/uploads/2023/06/event-hero-1-scaled.jpg",
            hero_source_name="CROSSROADS Maldives",
            hero_source_url="https://crossroadsmaldives.com/events/",
        ),
        _draft(
            registry,
            country="Maldives",
            city="South Male Atoll",
            property_name="Hard Rock Hotel Maldives",
            scene_type="luxury_hotel_mice",
            annual_visits=160_200,
            latitude=4.0206,
            longitude=73.4558,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="178 guestrooms, family suites, beach villas and overwater villas",
            source_name="Hard Rock Hotel Maldives MICE brochure",
            source_tier="Tier 1",
            source_url="https://hotel.hardrock.com/maldives/files/6016/hard_rock_hotel_maldives_mice_brochure.pdf",
            source_date=SOURCE_DATE,
            hero_url="https://hotel.hardrock.com/maldives/files/6016/Hard_Rock_Hotel_Maldives_Hero_Image.jpg",
            hero_source_name="Hard Rock Hotel Maldives",
            hero_source_url="https://hotel.hardrock.com/maldives",
        ),
        _draft(
            registry,
            country="Maldives",
            city="North Male Atoll",
            property_name="Sheraton Maldives Full Moon Resort & Spa",
            scene_type="luxury_hotel_mice",
            annual_visits=120_000,
            latitude=4.2505,
            longitude=73.5465,
            geocode_precision="hotel venue centroid",
            field_group="meeting_ballroom_area",
            indicator_name="meeting_ballroom_area",
            field_value="Jalsaa Room total event space: 5,037 sq ft; largest-space capacity: 100",
            source_name="Marriott",
            source_tier="Tier 1",
            source_url="https://www.marriott.com/en-us/hotels/mlesi-sheraton-maldives-full-moon-resort-and-spa/events/",
            source_date=SOURCE_DATE,
            hero_url="https://images.cvent.com/CSN/6a6db10d-b6c6-439b-9bb5-1d2d19235d58/images/ef66df7a5a6246e1bed2b9704ac7214f_LARGE!_!81fd34446a145ff954b746f54b4e0732.jpg",
            hero_source_name="Cvent Supplier Network",
            hero_source_url="https://www.cvent.com/venues/north-male-atoll/resort/sheraton-maldives-full-moon-resort-spa/venue-6a6db10d-b6c6-439b-9bb5-1d2d19235d58",
        ),
        _draft(
            registry,
            country="Maldives",
            city="North Male Atoll",
            property_name="Villa Nautica Paradise Island Resort",
            scene_type="luxury_hotel_mice",
            annual_visits=253_800,
            latitude=4.2845,
            longitude=73.5575,
            geocode_precision="hotel venue centroid",
            field_group="meeting_ballroom_area",
            indicator_name="meeting_ballroom_area",
            field_value="Total meeting space: 7,911 sq ft; 7 meeting rooms; seating capacity: 460; 282 guest rooms",
            source_name="Cvent Supplier Network",
            source_tier="Tier 2",
            source_url="https://www.cvent.com/venues/male/resort/villa-nautica-paradise-island-resort/venue-0c69cc71-c32f-4bea-8fd3-3602f3024bbc",
            source_date=SOURCE_DATE,
            hero_url="https://hotelcms-production.imgix.net/villaresorts.com/wp-content/uploads/2026/03/%40Rosslongphoto-Villa-Nautica-Drone-6-Large.jpg",
            hero_source_name="Villa Resorts",
            hero_source_url="https://villaresorts.com/villa-nautica/",
        ),
        _draft(
            registry,
            country="Maldives",
            city="South Male Atoll",
            property_name="SAii Lagoon Maldives",
            scene_type="luxury_hotel_mice",
            annual_visits=178_200,
            latitude=4.0218,
            longitude=73.4536,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="198 rooms and villas",
            source_name="Hilton Stories",
            source_tier="Tier 1",
            source_url="https://stories.hilton.com/apac/releases/curio-collection-by-hilton-opens-saii-lagoon-maldives",
            source_date="2019-09-19",
            hero_url="https://www.saiihotels.com/wp-content/uploads/2026/02/MLEGSQQ_Resort_Aerial_05-scaled.jpg",
            hero_source_name="SAii Lagoon Maldives",
            hero_source_url="https://www.saiihotels.com/lagoon-maldives/",
        ),
        _draft(
            registry,
            country="Maldives",
            city="North Male Atoll",
            property_name="Kurumba Maldives",
            scene_type="luxury_hotel_mice",
            annual_visits=162_000,
            latitude=4.2693,
            longitude=73.4945,
            geocode_precision="hotel venue centroid",
            field_group="keys",
            indicator_name="keys",
            field_value="180 rooms/villas",
            source_name="Wikipedia",
            source_tier="Tier 3",
            source_url="https://en.wikipedia.org/wiki/Kurumba_Maldives",
            source_date=SOURCE_DATE,
            hero_url="https://commons.wikimedia.org/wiki/Special:FilePath/Maldives%20-%20Kurumba%20Island.jpg",
            hero_source_name="Wikimedia Commons",
            hero_source_url="https://commons.wikimedia.org/wiki/File:Maldives_-_Kurumba_Island.jpg",
        ),
        _draft(
            registry,
            country="Maldives",
            city="Male",
            property_name="JEN Maldives Male by Shangri-La",
            scene_type="luxury_hotel_mice",
            annual_visits=108_000,
            latitude=4.1760,
            longitude=73.5117,
            geocode_precision="hotel venue centroid",
            field_group="ballroom_capacity",
            indicator_name="ballroom_capacity",
            field_value="Meeting capacity: 1 meeting room holding 120 people",
            source_name="Travel Weekly",
            source_tier="Tier 2",
            source_url="https://www.travelweekly.com/Hotels/Male-Maldives/Hotel-Jen-Male-p9430925",
            source_date=SOURCE_DATE,
            hero_url="https://images.trvl-media.com/lodging/3000000/2780000/2774300/2774299/a7e1e861.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
            hero_source_name="Expedia public hotel image metadata",
            hero_source_url="https://www.expedia.com/Male-Hotels-JEN-Maldives-Male-By-Shangri-La.h2774299.Hotel-Information",
        ),
    ]


def _draft(
    registry: dict[str, Any],
    *,
    country: str,
    city: str,
    property_name: str,
    scene_type: str,
    annual_visits: float | None,
    latitude: float,
    longitude: float,
    geocode_precision: str,
    field_group: str,
    indicator_name: str,
    field_value: str,
    source_name: str,
    source_tier: str,
    source_url: str,
    source_date: str,
    hero_url: str,
    hero_source_name: str,
    hero_source_url: str,
) -> CandidateDraft:
    bbox = registry["countries"][country]["bbox"]
    return CandidateDraft(
        region="Asia Pacific",
        country=country,
        city=city,
        property_name=property_name,
        scene_type=scene_type,
        annual_visits=float(annual_visits) if annual_visits is not None else None,
        latitude=latitude,
        longitude=longitude,
        geocode_precision=geocode_precision,
        map_source="public map coordinate cross-check",
        map_source_date=SOURCE_DATE,
        field_group=field_group,
        indicator_name=indicator_name,
        field_value=field_value,
        source_name=source_name,
        source_tier=source_tier,
        source_url=source_url,
        source_date=source_date,
        evidence_type="Direct",
        bbox=bbox,
        source_type=SOURCE_TYPE,
        content_text=f"{property_name}: {field_value}",
        hero_image={
            "url": hero_url,
            "alt_text": f"{property_name} public image",
            "source_name": hero_source_name,
            "source_url": hero_source_url,
            "source_date": source_date,
            "license": "Public web image metadata",
        },
    )


def _curation_summary(result: Any) -> dict[str, Any] | None:
    if result is None:
        return None
    return {
        "curation_run_id": result.curation_run_id,
        "new_evidence_count": result.new_evidence_count,
        "accepted_count": result.accepted_count,
        "updated_count": result.updated_count,
        "rejected_count": result.rejected_count,
        "countries": result.countries,
        "summary_path": str(result.summary_path),
        "report_path": str(result.report_path),
        "review_actions": result.review_actions,
    }


def _sync_summary(result: Any) -> dict[str, Any] | None:
    if result is None:
        return None
    return {
        "created": result.created,
        "run_id": str(result.run_id) if result.run_id else None,
        "candidate_count": result.candidate_count,
        "registry_candidate_count": result.registry_candidate_count,
        "blocked_candidate_count": result.blocked_candidate_count,
        "skipped_reason": result.skipped_reason,
        "derived_refresh": result.derived_refresh,
    }


def _render_report(summary: dict[str, Any]) -> str:
    rows = [
        "| Country | Property | Scene | Metric | Source |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in summary["accepted_candidates"]:
        rows.append(
            "| "
            + " | ".join(
                [
                    item["country"],
                    item["property_name"],
                    item["scene_type"],
                    item["indicator_name"],
                    item["source_name"],
                ]
            )
            + " |"
        )
    return "\n".join(
        [
            "# APAC High Value Seed Pass",
            "",
            f"- Countries: {', '.join(summary['countries'])}",
            f"- Planned: {summary['planned_count']}",
            f"- Accepted for write: {summary['accepted_for_write_count']}",
            f"- Rejected: {summary['rejected_count']}",
            f"- Firecrawl credits used: {summary['firecrawl_credits_used']}",
            f"- Overlay sync: {summary['overlay_sync']}",
            "",
            *rows,
            "",
        ]
    )


if __name__ == "__main__":
    main()
